### ISSUE TITLE
typo in install instructions

### ISSUE THREAD

**Issue by fwhelan** [jaleezyy/covid-19-sequencing#31]
Hi all- Andrew asked if I could do an independent test of your workflow (install and usage). I'll drop any issues I find here.

I think the install instructions should read `bash pipeline/scripts/get_data_dependencies.sh -d data -a MN908947.3` instead of `bash scripts/get_data_dependencies.sh -d data -a MN908947.3`

**Comment by jaleezyy** [comment]
Fixed typo with the correct `scripts` folder found in `pipeline/scripts/`.

**Comment by fwhelan** [comment]
Similar for `example_config.yaml` (`pipeline/example_config.yaml`).
